version: '3.7'

services:
  bot:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    user: "${UID}:${GID}"
    volumes:
      - ${TEMPLATE_PATH}:/opt/bot/templates:ro
      - ${NOTES_PATH}:/opt/bot/notes
      - /etc/localtime:/etc/localtime:ro
    networks:
      - bot

networks:
  bot: 